// This file is automatically generated by SConstruct.  Don't edit it by hand!
#ifndef EPS_EPSILON_CONFIG_H
#define EPS_EPSILON_CONFIG_H

#define EPS_LITTLE_ENDIAN
#define EPS_ASCII
#define EPS_X11
#define EPS_NDEBUG

#endif
